### ISSUE TITLE
Multiple url parameters

### ISSUE THREAD

**Issue by eliliam** [caolan/dispatch#8] opened 2016-11-30 15:44 UTC
I've ran into issues when it comes to multiple url arguments using the code here:
`"/data/:user/:type": function(req, res, user, type){ /*code*/}`
This seems to not work, whereas this code with one variable works:
`"/data/:user": function(req, res, user) {/*code*/}`

My question is, if this isn't how it works, how can I pass multiple URL arguments into the dispatcher?

**Comment by SebastianPozoga** [comment] 2019-05-14 16:03
@eliliam I tested your problem [here](https://github.com/SebastianPozoga/dispatch/blob/master/test/test-dispatch.js). Test like
```
exports['with multiple named param at end'] = function (test) {
    var request = {url: '/tests/123/456', method: 'GET'};
    dispatch({
        'GET /tests/:x/:y': function(req, res, x, y){
            test.equals(req, request);
            test.equals(res, 'response');
            test.equals(x, '123');
            test.equals(y, '456');
            test.done();
        }
    })(request, 'response');
};
```
work great. Can you replicate the problem?

**Comment by caolan** [comment] 2020-02-03 12:14
Closed as could not reproduce.

**Closed** 2020-02-03 12:14 UTC
